import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
const inter = Inter({ subsets: ["latin"] });
import Footer from "./_components/Footer";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full min-h-screen bg-[#000625] flex flex-col justify-between items-center">
          <Header />
          {children}
          <Footer />
        </div>
      </body>

    </html>
  );
}
